name: Decrypt SH Files in Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  decrypt-and-push:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies in container
      run: |
        apt-get update
        apt-get install -y bash procps sed git

    - name: Create decryption script
      run: |
        cat << 'EOF' > decrypt.sh
#!/bin/bash
if [[ $1 == "--installation-testing" ]]; then
  echo "ok"
  exit
fi

for args in $@; do
  if ! [[ -f $args ]]; then
    echo "$args not found."
    exit
  fi

  $args > /dev/null & child=$!
  sleep 0.03
  kill -STOP $child
  cat /proc/$child/cmdline | sed 's/.*\(#!\)/\1/; $d' > $args.decrypted.sh
  kill -TERM $child
done
EOF
        chmod +x decrypt.sh

    - name: Find and decrypt all SH files
      run: |
        find . -type f -name "*.sh" -not -name "decrypt.sh" -exec ./decrypt.sh {} \;

    - name: Commit decrypted files
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add '*.decrypted.sh' || echo "No decrypted files found"
        git commit -m "Add decrypted SH files" || echo "No changes to commit"
        git push
