name: Decrypt SH Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  decrypt-and-push:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run decryption script in Docker
      run: |
        docker run --rm -v $PWD:/workspace -w /workspace ubuntu:20.04 bash -c "
        apt-get update && apt-get install -y procps sed git &&
        
        echo '#!/bin/bash
        if [[ \$1 == \"--installation-testing\" ]]; then
          echo \"ok\"
          exit
        fi
        for args in \$@; do
          if ! [[ -f \$args ]]; then
            echo \"\$args not found.\"
            exit
          fi
          \$args > /dev/null & child=\$!
          sleep 0.03
          kill -STOP \$child
          cat /proc/\$child/cmdline | sed '\''s/.*\(#!\)/\1/; $d'\'' > \$args.decrypted.sh
          kill -TERM \$child
        done' > decrypt.sh && chmod +x decrypt.sh

        find . -name '*.sh' -not -name 'decrypt.sh' -exec ./decrypt.sh {} \;
        "

    - name: Commit decrypted files
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add '*.decrypted.sh' || echo "No decrypted files found"
        git commit -m "Add decrypted SH files" || echo "No changes to commit"
        git push
